import os
import argparse
import pandas as pd
import torch
from rdkit import Chem
from rdkit import RDLogger
from tqdm import tqdm
import pickle
from transformers import AutoTokenizer

# Block unnecessary warnings generated by RDKit
RDLogger.DisableLog('rdApp.*')

from ec_model import BioEC_EnzymePredictor, BioDualModalEncoder
from graph_utils import ATOM_FEAT_DIM
from ec_data import HierarchicalECDataset


def canonicalize_smiles(smi):
    if not smi or not isinstance(smi, str): return None
    try:
        smi = smi.replace(" ", "")
        mol = Chem.MolFromSmiles(smi)
        if mol is None: return None
        return Chem.MolToSmiles(mol, isomericSmiles=False)
    except:
        return None


def main(args):
    device = torch.device(args.device if torch.cuda.is_available() else 'cpu')
    print(f" Initializing data extraction and joint evaluation pipeline (Device: {device})")

    # ==========================================
    # Phase 1: Strict data alignment and physical isolation extraction
    # ==========================================
    print("\n[Phase 1] Loading and aligning datasets...")
    df_orig = pd.read_csv(args.orig_csv)
    df_clean = pd.read_csv(args.clean_csv)

    with open(args.src_txt, 'r') as f:
        src_lines = f.readlines()
    with open(args.tgt_txt, 'r') as f:
        tgt_lines = f.readlines()
    with open(args.predictions, 'r') as f:
        pred_lines = f.readlines()

    # Build a global hash composite key dictionary
    align_dict = {}
    for idx, (src_line, tgt_line) in enumerate(zip(src_lines, tgt_lines)):
        smi_p = canonicalize_smiles(src_line.strip())
        smi_r = canonicalize_smiles(tgt_line.strip())
        if smi_p and smi_r:
            key = (smi_p, smi_r)
            if key not in align_dict:
                align_dict[key] = []
            align_dict[key].append(idx)

    aligned_indices = set()
    aligned_data = {
        'orig': [], 'clean': [], 'src': [], 'tgt': [], 'pred': []
    }

    # Perform 1-to-1 matching
    for i in range(len(df_clean)):
        row_clean = df_clean.iloc[i]
        row_orig = df_orig.iloc[i]

        smi_p = canonicalize_smiles(str(row_clean['Products']))
        smi_r = canonicalize_smiles(str(row_clean['Reactiants']))

        key = (smi_p, smi_r)
        matched_indices = align_dict.get(key, [])

        if matched_indices:
            idx = matched_indices.pop(0)
            aligned_indices.add(idx)

            aligned_data['orig'].append(row_orig)
            aligned_data['clean'].append(row_clean)
            aligned_data['src'].append(src_lines[idx])
            aligned_data['tgt'].append(tgt_lines[idx])
            aligned_data['pred'].append(pred_lines[idx])

    # Find unmatched substrate data
    unmatched_indices = set(range(len(src_lines))) - aligned_indices

    # Save aligned golden dataset
    out_dir = os.path.join(os.path.dirname(args.clean_csv), "aligned_dataset")
    unmatched_dir = os.path.join(os.path.dirname(args.clean_csv), "unmatched_substrates")
    os.makedirs(out_dir, exist_ok=True)
    os.makedirs(unmatched_dir, exist_ok=True)

    pd.DataFrame(aligned_data['orig']).to_csv(os.path.join(out_dir, "aligned_orig.csv"), index=False)
    pd.DataFrame(aligned_data['clean']).to_csv(os.path.join(out_dir, "aligned_clean.csv"), index=False)

    with open(os.path.join(out_dir, "aligned_src.txt"), 'w') as f:
        f.writelines(aligned_data['src'])
    with open(os.path.join(out_dir, "aligned_tgt.txt"), 'w') as f:
        f.writelines(aligned_data['tgt'])
    with open(os.path.join(out_dir, "aligned_predictions.txt"), 'w') as f:
        f.writelines(aligned_data['pred'])

    # Save unmatched redundant/bad data
    with open(os.path.join(unmatched_dir, "unmatched_src.txt"), 'w') as f:
        f.writelines([src_lines[i] for i in sorted(unmatched_indices)])
    with open(os.path.join(unmatched_dir, "unmatched_tgt.txt"), 'w') as f:
        f.writelines([tgt_lines[i] for i in sorted(unmatched_indices)])
    with open(os.path.join(unmatched_dir, "unmatched_predictions.txt"), 'w') as f:
        f.writelines([pred_lines[i] for i in sorted(unmatched_indices)])

    print(f"  Data splitting complete!")
    print(f"   -> Successfully aligned {len(aligned_indices)} golden data entries, saved to {out_dir}")
    print(f"   -> Failed to align {len(unmatched_indices)} edge data entries, saved to {unmatched_dir}")

    # ==========================================
    # Phase 2: End-to-end real evaluation based on the golden dataset
    # ==========================================
    print("\n[Phase 2] Loading cofactor-free EC model for evaluation...")
    tokenizer = AutoTokenizer.from_pretrained(args.pretrained_path)
    with open(args.label_maps, 'rb') as f:
        label_maps = pickle.load(f)

    num_classes_list = [len(m) for m in label_maps]
    inv_label_maps = [{v: k for k, v in m.items()} for m in label_maps]

    encoder = BioDualModalEncoder(args.pretrained_path, atom_feat_dim=ATOM_FEAT_DIM)
    ec_model = BioEC_EnzymePredictor(encoder, num_classes_list, hidden_dim=512)
    ec_model.load_state_dict(torch.load(args.ec_ckpt, map_location=device))
    ec_model.to(device)
    ec_model.eval()

    # Use the newly generated aligned_clean.csv as baseline
    dummy_dataset = HierarchicalECDataset(os.path.join(out_dir, "aligned_clean.csv"), tokenizer, max_len=512,
                                          label_maps=label_maps, is_train=False)

    top1, top3, top5, top10 = 0, 0, 0, 0
    total = len(aligned_data['clean'])

    print("\n" + "=" * 50)
    print("  Starting end-to-end joint inference on golden dataset")
    print("=" * 50)

    for i in tqdm(range(total)):
        row_clean = aligned_data['clean'][i]

        target_reac_clean = canonicalize_smiles(str(row_clean['Reactiants']))
        true_ec = str(row_clean['EC'])

        # Directly read the recently aligned prediction results, now row numbers are absolutely 1-to-1 matched!
        parts = aligned_data['pred'][i].strip().split('\t')
        preds = parts[1:]

        hit_rank = -1
        pred_substrate_smi = None
        for rank, p_smi in enumerate(preds[:10]):
            if canonicalize_smiles(p_smi) == target_reac_clean:
                hit_rank = rank + 1
                # [Remove spaces to fix modality input]
                pred_substrate_smi = p_smi.replace(" ", "")
                break

        if hit_rank == -1: continue

        inputs_R = tokenizer(pred_substrate_smi, truncation=True, padding='max_length', max_length=512,
                             return_tensors='pt').to(device)
        inputs_P = tokenizer(str(row_clean['Products']), truncation=True, padding='max_length', max_length=512,
                             return_tensors='pt').to(device)

        x_R, adj_R = dummy_dataset.smiles_to_graph(pred_substrate_smi)
        x_P, adj_P = dummy_dataset.smiles_to_graph(str(row_clean['Products']))
        fp_dense_R, fp_indices_R = dummy_dataset.smiles_to_fp(pred_substrate_smi)
        fp_dense_P, fp_indices_P = dummy_dataset.smiles_to_fp(str(row_clean['Products']))

        fp_mask_R = torch.zeros(fp_indices_R.size(0), dtype=torch.bool).unsqueeze(0).to(device)
        fp_mask_P = torch.zeros(fp_indices_P.size(0), dtype=torch.bool).unsqueeze(0).to(device)

        with torch.no_grad():
            l1, l2, l3, l4 = ec_model(
                inputs_R['input_ids'], inputs_R['attention_mask'], x_R.unsqueeze(0).to(device),
                adj_R.unsqueeze(0).to(device),
                fp_indices_R.unsqueeze(0).to(device), fp_mask_R, fp_dense_R.unsqueeze(0).to(device),
                inputs_P['input_ids'], inputs_P['attention_mask'], x_P.unsqueeze(0).to(device),
                adj_P.unsqueeze(0).to(device),
                fp_indices_P.unsqueeze(0).to(device), fp_mask_P, fp_dense_P.unsqueeze(0).to(device),
                targets=None
            )

        pred_ec = f"{inv_label_maps[0].get(l1.argmax(dim=-1).item(), '0')}.{inv_label_maps[1].get(l2.argmax(dim=-1).item(), '0')}.{inv_label_maps[2].get(l3.argmax(dim=-1).item(), '0')}.{inv_label_maps[3].get(l4.argmax(dim=-1).item(), '0')}"

        if pred_ec == true_ec:
            if hit_rank == 1: top1 += 1
            if hit_rank <= 3: top3 += 1
            if hit_rank <= 5: top5 += 1
            if hit_rank <= 10: top10 += 1

    print("\n" + "=" * 50)
    print("  Final End-to-End Joint Accuracy (Golden Dataset)")
    print("=" * 50)
    print(f"Total evaluated samples: {total}")
    if total > 0:
        print(f"Joint Top-1:  {top1 / total:.2%}")
        print(f"Joint Top-3:  {top3 / total:.2%}")
        print(f"Joint Top-5:  {top5 / total:.2%}")
        print(f"Joint Top-10: {top10 / total:.2%}")
    print("=" * 50 + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--orig_csv', type=str, default='/data/stu1/ml_project/bioec_retro1/dataset/EC/test.csv')
    parser.add_argument('--clean_csv', type=str,
                        default='/data/stu1/ml_project/bioec_retro1/dataset/EC/clean_processed_csv/test.csv')
    parser.add_argument('--src_txt', type=str,
                        default='/data/stu1/ml_project/bioec_retro1/dataset/data_processed/tokenized/tokenized_src_test.txt')
    parser.add_argument('--tgt_txt', type=str,
                        default='/data/stu1/ml_project/bioec_retro1/dataset/data_processed/tokenized/tokenized_tgt_test.txt')
    parser.add_argument('--predictions', type=str,
                        default='/data/stu1/ml_project/bioec_retro1/FF/Finger3/prediction.txt')

    parser.add_argument('--pretrained_path', type=str,
                        default='/data/stu1/ml_project/bioec_retro1/ECfinger3/deepchem_bert')
    parser.add_argument('--ec_ckpt', type=str,
                        default='/data/stu1/ml_project/bioec_retro1/EC/save_ec_siamese_optimized/best_model.pt')
    parser.add_argument('--label_maps', type=str,
                        default='/data/stu1/ml_project/bioec_retro1/EC/save_ec_siamese_optimized/label_maps.pkl')
    parser.add_argument('--device', type=str, default='cuda:2')

    args = parser.parse_args()
    main(args)