import os
import argparse
import pandas as pd
import torch
from rdkit import Chem
from rdkit import RDLogger
from tqdm import tqdm
import pickle
from transformers import AutoTokenizer

# Block unnecessary warnings generated by RDKit
RDLogger.DisableLog('rdApp.*')

# Import core modules from your project
from ec_model import BioEC_EnzymePredictor, BioDualModalEncoder
from graph_utils import ATOM_FEAT_DIM
from ec_data import HierarchicalECDataset


def canonicalize_smiles(smi):
    """Canonicalize SMILES for precise matching"""
    if not smi or not isinstance(smi, str): return None
    try:
        smi = smi.replace(" ", "")
        mol = Chem.MolFromSmiles(smi)
        if mol is None: return None
        return Chem.MolToSmiles(mol, isomericSmiles=False)
    except:
        return None


def main(args):
    device = torch.device(args.device if torch.cuda.is_available() else 'cpu')
    print(f" Initializing true end-to-end joint evaluation (Device: {device})")

    # 1. Load data
    print("Loading datasets...")
    df_clean = pd.read_csv(args.clean_csv)

    with open(args.src_txt, 'r') as f:
        src_lines = f.readlines()
    with open(args.tgt_txt, 'r') as f:
        tgt_lines = f.readlines()
    with open(args.predictions, 'r') as f:
        pred_lines = f.readlines()

    print("Building alignment dictionary...")
    align_dict = {}
    for idx, (src_line, tgt_line) in enumerate(zip(src_lines, tgt_lines)):
        smi_p = canonicalize_smiles(src_line.strip())
        smi_r = canonicalize_smiles(tgt_line.strip())
        if smi_p and smi_r:
            key = (smi_p, smi_r)
            if key not in align_dict:
                align_dict[key] = []
            align_dict[key].append(idx)

    # 2. Load EC model
    print(f"Loading new cofactor-free weights: {args.ec_ckpt} ...")
    tokenizer = AutoTokenizer.from_pretrained(args.pretrained_path)
    with open(args.label_maps, 'rb') as f:
        label_maps = pickle.load(f)

    num_classes_list = [len(m) for m in label_maps]
    inv_label_maps = [{v: k for k, v in m.items()} for m in label_maps]

    encoder = BioDualModalEncoder(args.pretrained_path, atom_feat_dim=ATOM_FEAT_DIM)
    ec_model = BioEC_EnzymePredictor(encoder, num_classes_list, hidden_dim=512)
    ec_model.load_state_dict(torch.load(args.ec_ckpt, map_location=device))
    ec_model.to(device)
    ec_model.eval()

    dummy_dataset = HierarchicalECDataset(args.clean_csv, tokenizer, max_len=512, label_maps=label_maps, is_train=False)

    top1, top3, top5, top10 = 0, 0, 0, 0
    total = len(df_clean)
    aligned_count = 0

    print("\n" + "=" * 50)

    for i in tqdm(range(total)):
        row_clean = df_clean.iloc[i]

        target_prod_clean = canonicalize_smiles(str(row_clean['Products']))
        target_reac_clean = canonicalize_smiles(str(row_clean['Reactiants']))
        true_ec = str(row_clean['EC'])

        key = (target_prod_clean, target_reac_clean)
        matched_indices = align_dict.get(key, [])
        if not matched_indices: continue

        aligned_count += 1
        idx = matched_indices.pop(0)

        # A. Substrate validation
        parts = pred_lines[idx].strip().split('\t')
        preds = parts[1:]

        hit_rank = -1
        pred_substrate_smi = None
        for rank, p_smi in enumerate(preds[:10]):
            if canonicalize_smiles(p_smi) == target_reac_clean:
                hit_rank = rank + 1
                # ==========================================
                # [Fix] Eliminate spaces to save the inputs for GNN and fingerprint modalities!
                # ==========================================
                pred_substrate_smi = p_smi.replace(" ", "")
                break

        if hit_rank == -1: continue

        # B. Enzyme validation
        inputs_R = tokenizer(pred_substrate_smi, truncation=True, padding='max_length', max_length=512,
                             return_tensors='pt').to(device)
        inputs_P = tokenizer(str(row_clean['Products']), truncation=True, padding='max_length', max_length=512,
                             return_tensors='pt').to(device)

        # Now the extracted graphs and fingerprints are absolutely no longer all 0s!
        x_R, adj_R = dummy_dataset.smiles_to_graph(pred_substrate_smi)
        x_P, adj_P = dummy_dataset.smiles_to_graph(str(row_clean['Products']))
        fp_dense_R, fp_indices_R = dummy_dataset.smiles_to_fp(pred_substrate_smi)
        fp_dense_P, fp_indices_P = dummy_dataset.smiles_to_fp(str(row_clean['Products']))

        fp_mask_R = torch.zeros(fp_indices_R.size(0), dtype=torch.bool).unsqueeze(0).to(device)
        fp_mask_P = torch.zeros(fp_indices_P.size(0), dtype=torch.bool).unsqueeze(0).to(device)

        with torch.no_grad():
            l1, l2, l3, l4 = ec_model(
                inputs_R['input_ids'], inputs_R['attention_mask'], x_R.unsqueeze(0).to(device),
                adj_R.unsqueeze(0).to(device),
                fp_indices_R.unsqueeze(0).to(device), fp_mask_R, fp_dense_R.unsqueeze(0).to(device),
                inputs_P['input_ids'], inputs_P['attention_mask'], x_P.unsqueeze(0).to(device),
                adj_P.unsqueeze(0).to(device),
                fp_indices_P.unsqueeze(0).to(device), fp_mask_P, fp_dense_P.unsqueeze(0).to(device),
                targets=None
            )

        pred_ec = f"{inv_label_maps[0].get(l1.argmax(dim=-1).item(), '0')}.{inv_label_maps[1].get(l2.argmax(dim=-1).item(), '0')}.{inv_label_maps[2].get(l3.argmax(dim=-1).item(), '0')}.{inv_label_maps[3].get(l4.argmax(dim=-1).item(), '0')}"

        if pred_ec == true_ec:
            if hit_rank == 1: top1 += 1
            if hit_rank <= 3: top3 += 1
            if hit_rank <= 5: top5 += 1
            if hit_rank <= 10: top10 += 1

    print(f"Accuracy for Substrate and Enzyme EC Number")
    if aligned_count > 0:
        print(f"Joint Top-1:  {top1 / aligned_count:.2%}")
        print(f"Joint Top-3:  {top3 / aligned_count:.2%}")
        print(f"Joint Top-5:  {top5 / aligned_count:.2%}")
        print(f"Joint Top-10: {top10 / aligned_count:.2%}")
    print("=" * 50 + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--clean_csv', type=str,
                        default='/data/stu1/ml_project/bioec_retro1/dataset/EC/clean_processed_csv/test.csv')
    parser.add_argument('--src_txt', type=str,
                        default='/data/stu1/ml_project/bioec_retro1/dataset/data_processed/tokenized/tokenized_src_test.txt')
    parser.add_argument('--tgt_txt', type=str,
                        default='/data/stu1/ml_project/bioec_retro1/dataset/data_processed/tokenized/tokenized_tgt_test.txt')
    parser.add_argument('--predictions', type=str,
                        default='/data/stu1/ml_project/bioec_retro1/FF/Finger3/prediction.txt')

    parser.add_argument('--pretrained_path', type=str,
                        default='/data/stu1/ml_project/bioec_retro1/EC/deepchem_bert')
    parser.add_argument('--ec_ckpt', type=str,
                        default='/data/stu1/ml_project/bioec_retro1/EC/save_ec_siamese_optimized/best_model.pt')
    parser.add_argument('--label_maps', type=str,
                        default='/data/stu1/ml_project/bioec_retro1/EC/save_ec_siamese_optimized/label_maps.pkl')
    parser.add_argument('--device', type=str, default='cuda:2')

    args = parser.parse_args()
    main(args)