import argparse
import os
from rdkit import Chem
from rdkit import RDLogger
from tqdm import tqdm

# Block unnecessary warnings generated by RDKit
RDLogger.DisableLog('rdApp.*')


def canonicalize_smiles(smi):
    if not smi: return None
    try:
        smi = smi.replace(" ", "")
        mol = Chem.MolFromSmiles(smi)
        if mol is None: return None
        return Chem.MolToSmiles(mol, isomericSmiles=False)
    except:
        return None


def main(args):
    print(f" Starting evaluation of 613 unmatched edge data entries (Evaluating substrate accuracy only)")

    print(f"Loading Targets: {args.targets}")
    with open(args.targets, 'r') as f:
        targets = f.readlines()

    print(f"Loading Predictions: {args.predictions}")
    with open(args.predictions, 'r') as f:
        lines = f.readlines()

    if len(lines) != len(targets):
        print(f"Warning: Count mismatch. Targets: {len(targets)}, Preds: {len(lines)}. Truncating.")
        min_len = min(len(lines), len(targets))
        lines = lines[:min_len]
        targets = targets[:min_len]

    top1, top3, top5, top10 = 0, 0, 0, 0
    total = len(targets)
    valid_molecules = 0
    total_preds = 0

    parts = lines[0].strip().split('\t')
    beam_size = len(parts) - 1

    for i in tqdm(range(total)):
        canon_target = canonicalize_smiles(targets[i].strip())
        if canon_target is None: continue

        parts = lines[i].strip().split('\t')
        preds = parts[1:]

        # Pad to Beam size
        if len(preds) < beam_size: preds += [""] * (beam_size - len(preds))

        current_preds = []
        for p in preds:
            # Fix space issue
            p_clean = p.replace(" ", "") if p else ""
            c = canonicalize_smiles(p_clean)
            total_preds += 1
            if c:
                current_preds.append(c)
                valid_molecules += 1
            else:
                current_preds.append(None)

        if len(current_preds) > 0 and current_preds[0] == canon_target: top1 += 1
        if canon_target in current_preds[:3]: top3 += 1
        if canon_target in current_preds[:5]: top5 += 1
        if canon_target in current_preds[:10]: top10 += 1

    print("\n" + "=" * 50)
    print("  Evaluation Results for Unmatched Edge Data (613 entries)")
    print("=" * 50)
    print(f"Total evaluated: {total}")
    print(f"Model Validity (Legal generation rate): {valid_molecules / total_preds:.2%}")
    print("-" * 50)
    print(f"Substrate Top-1:  {top1 / total:.2%}")
    print(f"Substrate Top-3:  {top3 / total:.2%}")
    print(f"Substrate Top-5:  {top5 / total:.2%}")
    print(f"Substrate Top-10: {top10 / total:.2%}")
    print("=" * 50 + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    # Path points directly to the unmatched_substrates folder you just split out
    base_dir = '/data/stu1/ml_project/bioec_retro1/dataset/EC/clean_processed_csv/unmatched_substrates'
    parser.add_argument('--targets', default=f'{base_dir}/unmatched_tgt.txt')
    parser.add_argument('--predictions', default=f'{base_dir}/unmatched_predictions.txt')
    args = parser.parse_args()

    main(args)