save_data: /data/stu1/ml_project/bioec_retro1/single_retro/data/save
src_vocab: /data/stu1/ml_project/bioec_retro1/single_retro/data/vocab.src
tgt_vocab: /data/stu1/ml_project/bioec_retro1/single_retro/data/vocab.tgt

overwrite: False
share_vocab: False
seed: 20260527    # Change random seed to alter sample sampling order

data:
    corpus_1:
        path_src: /data/stu1/ml_project/bioec_retro1/dataset/USPTO/train_src.txt
        path_tgt: /data/stu1/ml_project/bioec_retro1/dataset/USPTO/train_tgt.txt
        weight: 0.0
    corpus_2:
        path_src: /data/stu1/ml_project/bioec_retro1/dataset/data_processed/tokenized/tokenized_src_train.txt
        path_tgt: /data/stu1/ml_project/bioec_retro1/dataset/data_processed/tokenized/tokenized_tgt_train.txt
        weight: 1.0
        dynamic_weight: false
    valid:
        path_src: /data/stu1/ml_project/bioec_retro1/dataset/data_processed/tokenized/tokenized_src_valid.txt
        path_tgt: /data/stu1/ml_project/bioec_retro1/dataset/data_processed/tokenized/tokenized_tgt_valid.txt

# Save to an independent subfolder under the train1 directory
save_model: /data/stu1/ml_project/bioec_retro1/train1/save3/finetune_seed3/model
save_checkpoint_steps: 2000
keep_checkpoint: 10
train_steps: 200000

gpu_ranks: [0]
world_size: 1
max_generator_batches: 32
batch_type: "sents"
batch_size: 32
accum_count: [8]

dropout: 0.1
d_model: 512
nhead: 8
num_layers: 4

max_graph_nodes: 150
lr: 0.0005