import argparse
import sys
import os
from rdkit import Chem
from rdkit import RDLogger
from tqdm import tqdm

# Block unnecessary warnings generated by RDKit
RDLogger.DisableLog('rdApp.*')


def canonicalize_smiles(smi):
    if not smi: return None
    try:
        smi = smi.replace(" ", "")
        mol = Chem.MolFromSmiles(smi)
        if mol is None: return None
        return Chem.MolToSmiles(mol, isomericSmiles=False)
    except:
        return None


def calculate_accuracy(target_file, pred_file, category_name):
    print(f"\n========== Evaluating {category_name.upper()} ==========")
    print(f"Loading Targets: {target_file}")
    with open(target_file, 'r') as f:
        targets = [line.strip().replace(" ", "") for line in f]

    print(f"Loading Predictions: {pred_file}")
    with open(pred_file, 'r') as f:
        lines = f.readlines()

    if len(lines) != len(targets):
        print(f"Warning: Count mismatch. Truncating.")
        min_len = min(len(lines), len(targets))
        lines = lines[:min_len]
        targets = targets[:min_len]

    top1, top3, top5, top10 = 0, 0, 0, 0
    total = len(targets)
    valid_molecules = 0
    total_preds = 0

    if total == 0:
        print("Error: Target file is empty.")
        return

    parts = lines[0].strip().split('\t')
    beam_size = len(parts) - 1
    print(f"Detected Beam Size: {beam_size}")

    for i in tqdm(range(total), desc=f"Scoring {category_name}"):
        canon_target = canonicalize_smiles(targets[i])
        if canon_target is None: continue

        parts = lines[i].strip().split('\t')
        preds = parts[1:]
        if len(preds) < beam_size: preds += [""] * (beam_size - len(preds))

        current_preds = []
        for p in preds:
            c = canonicalize_smiles(p)
            total_preds += 1
            if c:
                current_preds.append(c)
                valid_molecules += 1
            else:
                current_preds.append(None)

        if current_preds and current_preds[0] == canon_target: top1 += 1
        if canon_target in current_preds[:3]: top3 += 1
        if canon_target in current_preds[:5]: top5 += 1
        if canon_target in current_preds[:10]: top10 += 1

    print(f"\n--- {category_name.upper()} Results ---")
    print(f"Top-1:  {top1 / total:.2%}")
    print(f"Top-3:  {top3 / total:.2%}")
    print(f"Top-5:  {top5 / total:.2%}")
    print(f"Top-10: {top10 / total:.2%}")
    print("=" * 45 + "\n")


if __name__ == "__main__":
    # --- Batch testing list ---
    categories = ['flavonoids', 'phenols', 'steroids', 'terpenes']

    # Path where the actual targets are located (tgt files)
    base_tgt_dir = '/data/stu1/ml_project/code/dataset/natural_data/mentor_testset/category_processed/clean'

    # Path where the previous code output the prediction results (pred files)
    base_pred_dir = '/data/stu1/ml_project/code/dataset/natural_data/mentor_testset/category_processed/outputs'

    for cat in categories:
        tgt_file = os.path.join(base_tgt_dir, f"{cat}_tgt.txt")
        pred_file = os.path.join(base_pred_dir, f"{cat}_pred.txt")

        # Check if the files exist to prevent the script from crashing if a file hasn't finished processing
        if not os.path.exists(tgt_file):
            print(f"Target file missing: {tgt_file}")
            continue
        if not os.path.exists(pred_file):
            print(f"Prediction file missing: {pred_file}")
            continue

        calculate_accuracy(tgt_file, pred_file, category_name=cat)