import numpy as np
from rdkit import Chem
from rdkit import RDLogger

# Block unnecessary warnings generated by RDKit
RDLogger.DisableLog('rdApp.*')

# Updated feature dimension (44 symbols + 11 degrees + 5 Hs + 6 valences + 1 aromatic + 3 chiral = 70)
ATOM_FEAT_DIM = 70


def one_of_k_encoding(x, allowable_set):
    """Maps an input to a one-hot encoding based on an allowable set."""
    if x not in allowable_set:
        raise Exception(f"input {x} not in allowable set{allowable_set}")
    return list(map(lambda s: x == s, allowable_set))


def one_of_k_encoding_unk(x, allowable_set):
    """Maps an input to a one-hot encoding, mapping unseen inputs to the last element (Unknown)."""
    if x not in allowable_set:
        x = allowable_set[-1]
    return list(map(lambda s: x == s, allowable_set))


def get_atom_features(atom):
    """
    Extracts atomic features using RDKit and converts them to a one-hot feature vector.
    Includes chirality features. Returns a numpy array of dimension ATOM_FEAT_DIM (70).
    """
    symbol_list = ['C', 'N', 'O', 'S', 'F', 'Si', 'P', 'Cl', 'Br', 'Mg', 'Na', 'Ca', 'Fe', 'As', 'Al', 'I', 'B', 'V',
                   'K', 'Tl', 'Yb', 'Sb', 'Sn', 'Ag', 'Pd', 'Co', 'Se', 'Ti', 'Zn', 'H', 'Li', 'Ge', 'Cu', 'Au', 'Ni',
                   'Cd', 'In', 'Mn', 'Zr', 'Cr', 'Pt', 'Hg', 'Pb', 'Unknown']

    chiral_tag = atom.GetChiralTag()
    chiral_features = one_of_k_encoding_unk(chiral_tag,
                                            [Chem.rdchem.ChiralType.CHI_UNSPECIFIED,
                                             Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CW,
                                             Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CCW])

    results = one_of_k_encoding_unk(atom.GetSymbol(), symbol_list) + \
              one_of_k_encoding(atom.GetDegree(), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) + \
              one_of_k_encoding_unk(atom.GetTotalNumHs(), [0, 1, 2, 3, 4]) + \
              one_of_k_encoding_unk(atom.GetImplicitValence(), [0, 1, 2, 3, 4, 5]) + \
              [atom.GetIsAromatic()] + \
              chiral_features

    return np.array(results).astype(np.float32)


def smiles_to_graph(smiles, max_len=150):
    """
    Converts a SMILES string into a node feature matrix and a multi-relational adjacency matrix.
    Includes safeguards for handling invalid or empty molecules.
    """
    mol = Chem.MolFromSmiles(smiles)

    adj = np.zeros((4, max_len, max_len), dtype=np.float32)
    features = np.zeros((max_len, ATOM_FEAT_DIM), dtype=np.float32)

    # === [Core Fix] Handle bad/empty molecules ===
    # If parsing fails, or the molecule has no atoms
    if mol is None or mol.GetNumAtoms() == 0:
        # Manually create a dummy atom of "Unknown" type
        # Ensure the first position of features is not all 0s, so the Mask won't evaluate to all True
        features[0, -1] = 1.0  # Assuming the last dimension is Chirality or Unknown
        features[0, 0] = 1.0   # Assign some arbitrary values to ensure sum != 0

        # Add self-loops to this dummy atom to prevent errors during GCN convolution
        for ch in range(4):
            adj[ch, 0, 0] = 1.0

        return features, adj
    # =============================================

    num_atoms = mol.GetNumAtoms()
    curr_atoms = min(num_atoms, max_len)

    for i in range(curr_atoms):
        atom = mol.GetAtomWithIdx(i)
        features[i] = get_atom_features(atom)

    for bond in mol.GetBonds():
        u = bond.GetBeginAtomIdx()
        v = bond.GetEndAtomIdx()
        if u >= max_len or v >= max_len: continue

        bond_type = bond.GetBondType()
        if bond_type == Chem.rdchem.BondType.SINGLE:
            ch = 0
        elif bond_type == Chem.rdchem.BondType.DOUBLE:
            ch = 1
        elif bond_type == Chem.rdchem.BondType.TRIPLE:
            ch = 2
        elif bond_type == Chem.rdchem.BondType.AROMATIC:
            ch = 3
        else:
            ch = 0

        adj[ch, u, v] = 1.0
        adj[ch, v, u] = 1.0

    # Add self-loops to the diagonal for each bond type channel
    for ch in range(4):
        adj[ch, :curr_atoms, :curr_atoms] += np.eye(curr_atoms)

    return features, adj