import argparse
import sys
import os
from rdkit import Chem
from rdkit import RDLogger
from tqdm import tqdm

# Block unnecessary warnings generated by RDKit
RDLogger.DisableLog('rdApp.*')


def canonicalize_smiles(smi):
    """
    Canonicalizes a SMILES string.
    Removes spaces and returns the non-isomeric canonical SMILES.
    Returns None if parsing fails.
    """
    if not smi: return None
    try:
        smi = smi.replace(" ", "")
        mol = Chem.MolFromSmiles(smi)
        if mol is None: return None
        return Chem.MolToSmiles(mol, isomericSmiles=False)
    except:
        return None


def calculate_accuracy(target_file, pred_file):
    """
    Calculates Top-1, Top-3, Top-5, and Top-10 accuracies by comparing
    the predicted SMILES sequences against the ground truth targets.
    """
    print(f"Loading Targets: {target_file}")
    with open(target_file, 'r') as f:
        targets = [line.strip().replace(" ", "") for line in f]

    print(f"Loading Predictions: {pred_file}")
    with open(pred_file, 'r') as f:
        lines = f.readlines()

    if len(lines) != len(targets):
        print(f"Warning: Count mismatch. Truncating.")
        min_len = min(len(lines), len(targets))
        lines = lines[:min_len]
        targets = targets[:min_len]

    top1, top3, top5, top10 = 0, 0, 0, 0
    total = len(targets)
    valid_molecules = 0
    total_preds = 0

    parts = lines[0].strip().split('\t')
    beam_size = len(parts) - 1
    print(f"Detected Beam Size: {beam_size}")

    for i in tqdm(range(total), desc="Evaluating Accuracy"):
        canon_target = canonicalize_smiles(targets[i])
        if canon_target is None: continue

        parts = lines[i].strip().split('\t')
        preds = parts[1:]

        # Pad to match beam size if necessary
        if len(preds) < beam_size:
            preds += [""] * (beam_size - len(preds))

        current_preds = []
        for p in preds:
            c = canonicalize_smiles(p)
            total_preds += 1
            if c:
                current_preds.append(c)
                valid_molecules += 1
            else:
                current_preds.append(None)

        if current_preds[0] == canon_target: top1 += 1
        if canon_target in current_preds[:3]: top3 += 1
        if canon_target in current_preds[:5]: top5 += 1
        if canon_target in current_preds[:10]: top10 += 1

    print("\n" + "=" * 40)
    print(" General Evaluation Results")
    print("=" * 40)
    print(f"Top-1:  {top1 / total:.2%}")
    print(f"Top-3:  {top3 / total:.2%}")
    print(f"Top-5:  {top5 / total:.2%}")
    print(f"Top-10: {top10 / total:.2%}")
    print("=" * 40 + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--targets',
                        default='/data/stu1/ml_project/bioec_retro1/dataset/data_processed/tokenized/tokenized_tgt_test.txt')
    parser.add_argument('--predictions', default='/data/stu1/ml_project/bioec_retro1/FF/Finger3/prediction.txt')
    args = parser.parse_args()

    calculate_accuracy(args.targets, args.predictions)